name: JMeter Performance Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  performance-test:
    runs-on: ubuntu-latest  # También puedes usar windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # JMeter requiere Java 8+
          distribution: 'temurin'

      - name: Download JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.2.zip
          unzip apache-jmeter-5.6.2.zip
          echo "$PWD/apache-jmeter-5.6.2/bin" >> $GITHUB_PATH
      
      - name: Create results directory
        run: mkdir -p results
      
      #- name: Copy JMeter Test Plan
      #  run: cp test_rendimiento.jmx apache-jmeter-5.6.2/bin/
      
      - name: Create report directory
        run: mkdir -p results/report

      - name: Run JMeter Test
        run: |
          jmeter -n -t test_rendimiento.jmx -l results/result.jtl -e -o results/report

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: results/report